import type { Property, Testimonial, Service, Zone, Stat } from './types'

export const properties: Property[] = [
  {
    id: '1',
    slug: 'casa-moderna-el-palomar',
    title: 'Casa Moderna en El Palomar',
    operationType: 'venta',
    propertyType: 'casa',
    address: 'Av. Mosconi 2450',
    neighborhood: 'El Palomar',
    city: 'Buenos Aires',
    price: 185000,
    currency: 'USD',
    shortDescription: 'Espectacular casa moderna con amplios espacios y excelente luminosidad.',
    longDescription: 'Ubicada en una de las mejores zonas de El Palomar, esta casa moderna ofrece un diseño contemporáneo con acabados de primera calidad. Cuenta con living-comedor integrado, cocina equipada, suite principal con vestidor y baño en suite, dos dormitorios adicionales, y un hermoso jardín con parrilla. Ideal para familias que buscan confort y estilo.',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    garages: 2,
    coveredArea: 180,
    totalArea: 320,
    age: 5,
    condition: 'excelente',
    features: ['balcon', 'terraza', 'jardin', 'parrilla', 'pileta', 'seguridad', 'aire-acondicionado', 'calefaccion'],
    images: ['/images/properties/casa-1.jpg', '/images/properties/casa-1-2.jpg', '/images/properties/casa-1-3.jpg'],
    featured: true,
    creditReady: true,
    location: { lat: -34.6037, lng: -58.5986 },
    propertyCode: 'AB-001',
    createdAt: '2024-03-15',
  },
  {
    id: '2',
    slug: 'departamento-ciudad-jardin',
    title: 'Departamento Premium Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'departamento',
    address: 'Calle Las Flores 890',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 125000,
    currency: 'USD',
    shortDescription: 'Moderno departamento de 2 ambientes con balcón terraza y vista panorámica.',
    longDescription: 'Excelente departamento en edificio de categoría con amenities completos. Cuenta con living-comedor con salida a balcón terraza, cocina integrada de diseño, dormitorio en suite y toilette. El edificio ofrece pileta, gimnasio, sum y seguridad 24hs. Ubicación privilegiada cerca de todos los servicios.',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    garages: 1,
    coveredArea: 65,
    totalArea: 75,
    age: 2,
    condition: 'nuevo',
    features: ['balcon', 'terraza', 'pileta', 'gimnasio', 'seguridad', 'aire-acondicionado'],
    images: ['/images/properties/depto-1.jpg', '/images/properties/depto-1-2.jpg'],
    featured: true,
    creditReady: true,
    location: { lat: -34.5875, lng: -58.6123 },
    propertyCode: 'AB-002',
    createdAt: '2024-03-10',
  },
  {
    id: '3',
    slug: 'ph-luminoso-zona-oeste',
    title: 'PH Luminoso en Zona Oeste',
    operationType: 'alquiler',
    propertyType: 'ph',
    address: 'Pasaje del Sol 456',
    neighborhood: 'El Palomar',
    city: 'Buenos Aires',
    price: 280000,
    currency: 'ARS',
    shortDescription: 'Hermoso PH reciclado con patio propio y entrada independiente.',
    longDescription: 'PH totalmente reciclado a nuevo con materiales de primera calidad. Planta baja con living-comedor, cocina y patio. Planta alta con dos dormitorios y baño completo. Lavadero independiente. Sin expensas. Ideal para quienes buscan privacidad y espacios verdes propios.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    garages: 0,
    coveredArea: 85,
    totalArea: 110,
    age: 0,
    condition: 'excelente',
    features: ['patio', 'parrilla', 'lavadero'],
    images: ['/images/properties/ph-1.jpg', '/images/properties/ph-1-2.jpg'],
    featured: false,
    creditReady: false,
    location: { lat: -34.6012, lng: -58.5945 },
    propertyCode: 'AB-003',
    createdAt: '2024-03-08',
  },
  {
    id: '4',
    slug: 'lote-residencial-ciudad-jardin',
    title: 'Lote Residencial en Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'lote',
    address: 'Barrio Cerrado Los Robles',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 95000,
    currency: 'USD',
    shortDescription: 'Excelente lote en barrio cerrado con todos los servicios.',
    longDescription: 'Lote ideal para construir la casa de tus sueños en uno de los barrios más exclusivos de Ciudad Jardín. El barrio cuenta con seguridad 24hs, calles pavimentadas, red de gas natural, electricidad y cloacas. Club house con pileta, canchas de tenis y espacios verdes.',
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    garages: 0,
    coveredArea: 0,
    totalArea: 450,
    age: 0,
    condition: 'nuevo',
    features: ['seguridad', 'pileta', 'club-house'],
    images: ['/images/properties/lote-1.jpg'],
    featured: true,
    creditReady: false,
    location: { lat: -34.5912, lng: -58.6087 },
    propertyCode: 'AB-004',
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    slug: 'oficina-comercial-centro',
    title: 'Oficina Comercial Centro',
    operationType: 'alquiler',
    propertyType: 'oficina',
    address: 'Av. San Martín 1200',
    neighborhood: 'El Palomar',
    city: 'Buenos Aires',
    price: 450000,
    currency: 'ARS',
    shortDescription: 'Oficina en ubicación estratégica ideal para profesionales.',
    longDescription: 'Amplia oficina en pleno centro comercial de El Palomar. Cuenta con recepción, dos despachos privados, sala de reuniones y office. Edificio con ascensor, portero y excelente mantenimiento. A pasos de transporte público y todos los servicios.',
    rooms: 4,
    bedrooms: 0,
    bathrooms: 1,
    garages: 0,
    coveredArea: 80,
    totalArea: 80,
    age: 15,
    condition: 'muy-bueno',
    features: ['aire-acondicionado', 'ascensor'],
    images: ['/images/properties/oficina-1.jpg'],
    featured: false,
    creditReady: false,
    location: { lat: -34.6045, lng: -58.5978 },
    propertyCode: 'AB-005',
    createdAt: '2024-03-01',
  },
  {
    id: '6',
    slug: 'casa-quinta-zona-oeste',
    title: 'Casa Quinta en Zona Oeste',
    operationType: 'venta',
    propertyType: 'casa',
    address: 'Camino del Buen Ayre 4500',
    neighborhood: 'Zona Oeste',
    city: 'Buenos Aires',
    price: 320000,
    currency: 'USD',
    shortDescription: 'Impresionante casa quinta con pileta y parque de 2000m².',
    longDescription: 'Espectacular propiedad ideal para quienes buscan espacio y tranquilidad sin alejarse de la ciudad. Casa principal de 250m² con living con hogar, cocina-comedor, 4 dormitorios y 3 baños. Quincho cerrado con parrilla, pileta de 10x5m, cancha de paddle y amplio parque parquizado. Galpón para guardado de vehículos.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    garages: 3,
    coveredArea: 250,
    totalArea: 2000,
    age: 12,
    condition: 'excelente',
    features: ['jardin', 'parrilla', 'pileta', 'quincho', 'dependencia'],
    images: ['/images/properties/quinta-1.jpg', '/images/properties/quinta-1-2.jpg', '/images/properties/quinta-1-3.jpg'],
    featured: true,
    creditReady: true,
    location: { lat: -34.5823, lng: -58.6234 },
    propertyCode: 'AB-006',
    createdAt: '2024-02-28',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'María Fernández',
    role: 'Compradora',
    content: 'Excelente experiencia con Alvarez Brokers. Nos acompañaron en todo el proceso de compra con profesionalismo y dedicación. Encontramos la casa de nuestros sueños gracias a su asesoramiento.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Carlos Rodríguez',
    role: 'Vendedor',
    content: 'Vendí mi departamento en tiempo récord y al precio que esperaba. El equipo de tasación fue muy preciso y la estrategia comercial impecable. Totalmente recomendables.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Laura Martínez',
    role: 'Inversora',
    content: 'Confío en Alvarez Brokers para todas mis inversiones inmobiliarias. Su conocimiento del mercado de Zona Oeste es incomparable y siempre encuentran las mejores oportunidades.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Roberto Sánchez',
    role: 'Propietario',
    content: 'Alquilé mi propiedad a través de ellos y el proceso fue impecable. La selección de inquilinos, el contrato y el seguimiento posterior fueron de primer nivel.',
    rating: 5,
  },
]

export const services: Service[] = [
  {
    id: '1',
    title: 'Venta de Inmuebles',
    description: 'Comercializamos tu propiedad con estrategias efectivas y presencia en los principales portales inmobiliarios.',
    icon: 'home',
    href: '/servicios#venta',
  },
  {
    id: '2',
    title: 'Alquileres',
    description: 'Gestionamos el alquiler de tu propiedad con selección rigurosa de inquilinos y contratos seguros.',
    icon: 'key',
    href: '/servicios#alquiler',
  },
  {
    id: '3',
    title: 'Tasaciones',
    description: 'Determinamos el valor real de mercado de tu propiedad con análisis profesional y datos actualizados.',
    icon: 'chart',
    href: '/tasaciones',
  },
  {
    id: '4',
    title: 'Asesoramiento Legal',
    description: 'Respaldo legal completo en todas las operaciones inmobiliarias para tu tranquilidad.',
    icon: 'shield',
    href: '/servicios#legal',
  },
  {
    id: '5',
    title: 'Inversiones',
    description: 'Identificamos oportunidades de inversión con análisis de rentabilidad y potencial de valorización.',
    icon: 'trending',
    href: '/inversiones',
  },
  {
    id: '6',
    title: 'Búsqueda Personalizada',
    description: 'Encontramos la propiedad ideal según tus necesidades específicas y presupuesto.',
    icon: 'search',
    href: '/contacto',
  },
]

export const zones: Zone[] = [
  {
    id: '1',
    name: 'El Palomar',
    description: 'Zona residencial con excelente conectividad y todos los servicios.',
    image: '/images/zones/el-palomar.jpg',
    propertyCount: 45,
  },
  {
    id: '2',
    name: 'Ciudad Jardín',
    description: 'Barrio exclusivo con amplios espacios verdes y calidad de vida.',
    image: '/images/zones/ciudad-jardin.jpg',
    propertyCount: 32,
  },
  {
    id: '3',
    name: 'Zona Oeste',
    description: 'Amplia cobertura en toda la región con las mejores oportunidades.',
    image: '/images/zones/zona-oeste.jpg',
    propertyCount: 78,
  },
]

export const stats: Stat[] = [
  { label: 'Años de Experiencia', value: 25, suffix: '+' },
  { label: 'Propiedades Vendidas', value: 1200, suffix: '+' },
  { label: 'Clientes Satisfechos', value: 3500, suffix: '+' },
  { label: 'Tasaciones Realizadas', value: 5000, suffix: '+' },
]

export const propertyTypes = [
  { value: 'casa', label: 'Casa' },
  { value: 'departamento', label: 'Departamento' },
  { value: 'ph', label: 'PH' },
  { value: 'lote', label: 'Lote' },
  { value: 'oficina', label: 'Oficina' },
  { value: 'local', label: 'Local' },
  { value: 'cochera', label: 'Cochera' },
  { value: 'galpon', label: 'Galpón' },
]

export const operationTypes = [
  { value: 'venta', label: 'Venta' },
  { value: 'alquiler', label: 'Alquiler' },
  { value: 'temporal', label: 'Temporal' },
]

export const neighborhoods = [
  { value: 'el-palomar', label: 'El Palomar' },
  { value: 'ciudad-jardin', label: 'Ciudad Jardín' },
  { value: 'zona-oeste', label: 'Zona Oeste' },
]

export const features = [
  { value: 'balcon', label: 'Balcón' },
  { value: 'terraza', label: 'Terraza' },
  { value: 'patio', label: 'Patio' },
  { value: 'jardin', label: 'Jardín' },
  { value: 'parrilla', label: 'Parrilla' },
  { value: 'pileta', label: 'Pileta' },
  { value: 'lavadero', label: 'Lavadero' },
  { value: 'cocina-separada', label: 'Cocina Separada' },
  { value: 'dependencia', label: 'Dependencia' },
  { value: 'seguridad', label: 'Seguridad' },
  { value: 'aire-acondicionado', label: 'Aire Acondicionado' },
  { value: 'calefaccion', label: 'Calefacción' },
  { value: 'gimnasio', label: 'Gimnasio' },
  { value: 'quincho', label: 'Quincho' },
  { value: 'ascensor', label: 'Ascensor' },
  { value: 'club-house', label: 'Club House' },
]
