import type { Property, Service, Zone } from './types'

// Catálogo demo de Tacchino Propiedades.
// Los datos de cada propiedad (dirección, precio, superficie, ambientes)
// corresponden a la base provista por el cliente. Las fotografías son
// imágenes de referencia (Unsplash) hasta contar con material fotográfico
// propio de cada inmueble.
export const properties: Property[] = [
  {
    id: '1',
    slug: 'chalet-de-las-violetas-ciudad-jardin',
    title: 'Chalet 4 ambientes en Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'casa',
    address: 'De las Violetas 6159',
    neighborhood: 'Ciudad Jardín Lomas del Palomar',
    city: 'Buenos Aires',
    price: 148000,
    currency: 'USD',
    shortDescription: 'Chalet de 4 ambientes con 3 dormitorios y cochera en el corazón de Ciudad Jardín Lomas del Palomar.',
    longDescription: 'Chalet de 151 m² totales distribuidos en 4 ambientes, ideal para familias que buscan una vivienda consolidada en una de las zonas más tradicionales de Ciudad Jardín Lomas del Palomar. Cuenta con 3 dormitorios, 2 baños y cochera para 1 vehículo. Ubicación tranquila, arbolada y a metros de los principales accesos de la zona.',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    coveredArea: 151,
    totalArea: 151,
    age: 0,
    condition: 'muy-bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: true,
    creditReady: false,
    reserved: false,
    isNew: false,
    location: { lat: -34.6017, lng: -58.5964 },
    propertyCode: 'TP-001',
    createdAt: '2026-08-10',
  },
  {
    id: '2',
    slug: 'duplex-la-cautiva-villa-bosch',
    title: 'Dúplex 4 ambientes en Villa Bosch',
    operationType: 'venta',
    propertyType: 'duplex',
    address: 'La Cautiva 6393',
    neighborhood: 'Villa Bosch',
    city: 'Buenos Aires',
    price: 134000,
    currency: 'USD',
    shortDescription: 'Dúplex de 4 ambientes, 3 dormitorios y cochera, apto crédito, en Villa Bosch.',
    longDescription: 'Dúplex de 113 m² distribuidos en dos plantas, con 4 ambientes, 3 dormitorios y 1 baño. Cuenta con cochera para 1 vehículo y es apto para operaciones con financiación bancaria. Ubicado en una de las zonas de mayor crecimiento de Villa Bosch, cerca de comercios y transporte público.',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 1,
    garages: 1,
    coveredArea: 113,
    totalArea: 113,
    age: 0,
    condition: 'muy-bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: true,
    creditReady: true,
    reserved: true,
    isNew: false,
    location: { lat: -34.6112, lng: -58.5687 },
    propertyCode: 'TP-002',
    createdAt: '2026-08-05',
  },
  {
    id: '3',
    slug: 'departamento-jacarandaes-ciudad-jardin',
    title: 'Departamento 2 ambientes en Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'departamento',
    address: 'De los Jacarandaes 6154',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 88000,
    currency: 'USD',
    shortDescription: 'Departamento de 2 ambientes con balcón en Ciudad Jardín.',
    longDescription: 'Departamento de 44 m² con living-comedor, 1 dormitorio, 1 baño y balcón. Una opción compacta y luminosa para quienes buscan dar el primer paso en Ciudad Jardín, cerca de espacios verdes y con fácil acceso a los principales corredores de la zona.',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    garages: 0,
    coveredArea: 44,
    totalArea: 44,
    age: 0,
    condition: 'bueno',
    features: ['balcon'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: false,
    creditReady: false,
    reserved: false,
    isNew: false,
    location: { lat: -34.5978, lng: -58.6001 },
    propertyCode: 'TP-003',
    createdAt: '2026-07-28',
  },
  {
    id: '4',
    slug: 'departamento-margaritas-ciudad-jardin',
    title: 'Departamento 3 ambientes en Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'departamento',
    address: 'De las Margaritas 6286',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 79000,
    currency: 'USD',
    shortDescription: 'Departamento de 3 ambientes, 2 dormitorios, apto crédito, en Ciudad Jardín.',
    longDescription: 'Departamento de 56 m² con 3 ambientes, 2 dormitorios y 1 baño, apto para operaciones con financiación bancaria. Muy buena relación entre superficie y ubicación, a pasos de los principales accesos de Ciudad Jardín.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    garages: 0,
    coveredArea: 56,
    totalArea: 56,
    age: 0,
    condition: 'bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1598928636135-d146006ff4be?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: true,
    creditReady: true,
    reserved: false,
    isNew: false,
    location: { lat: -34.5983, lng: -58.5992 },
    propertyCode: 'TP-004',
    createdAt: '2026-08-15',
  },
  {
    id: '5',
    slug: 'chalet-aviador-koehl-ciudad-jardin',
    title: 'Chalet 5 ambientes en Ciudad Jardín',
    operationType: 'venta',
    propertyType: 'casa',
    address: 'Aviador Koehl 2375',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 172000,
    currency: 'USD',
    shortDescription: 'Amplio chalet de 5 ambientes, 4 dormitorios y cochera en Ciudad Jardín.',
    longDescription: 'Chalet de 210 m² con 5 ambientes, 4 dormitorios, 2 baños y cochera para 1 vehículo. Una propuesta pensada para familias numerosas que buscan amplitud y una ubicación consolidada dentro de Ciudad Jardín.',
    rooms: 5,
    bedrooms: 4,
    bathrooms: 2,
    garages: 1,
    coveredArea: 210,
    totalArea: 210,
    age: 0,
    condition: 'muy-bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585153490-76fb20a32601?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: true,
    creditReady: false,
    reserved: false,
    isNew: true,
    location: { lat: -34.5947, lng: -58.6019 },
    propertyCode: 'TP-005',
    createdAt: '2026-08-20',
  },
  {
    id: '6',
    slug: 'departamento-gualeguay-el-palomar',
    title: 'Monoambiente en El Palomar',
    operationType: 'venta',
    propertyType: 'departamento',
    address: 'Gualeguay 611',
    neighborhood: 'El Palomar',
    city: 'Buenos Aires',
    price: 45000,
    currency: 'USD',
    shortDescription: 'Monoambiente apto crédito en El Palomar. Excelente opción para inversión o primera vivienda.',
    longDescription: 'Monoambiente de 30 m² con 1 baño, apto para operaciones con financiación bancaria. Excelente opción para inversión o primera vivienda, en una ubicación céntrica de El Palomar con fácil acceso a transporte y comercios.',
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    garages: 0,
    coveredArea: 30,
    totalArea: 30,
    age: 0,
    condition: 'bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560449017-7d3d40080d9b?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: true,
    creditReady: true,
    reserved: false,
    isNew: false,
    location: { lat: -34.6089, lng: -58.6109 },
    propertyCode: 'TP-006',
    createdAt: '2026-08-01',
  },
  {
    id: '7',
    slug: 'monoambiente-alquiler-boulevard-san-martin-ciudad-jardin',
    title: 'Monoambiente en alquiler en Ciudad Jardín',
    operationType: 'alquiler',
    propertyType: 'departamento',
    address: 'Boulevard San Martín 3082',
    neighborhood: 'Ciudad Jardín',
    city: 'Buenos Aires',
    price: 500000,
    currency: 'ARS',
    shortDescription: 'Monoambiente en alquiler sobre Boulevard San Martín, Ciudad Jardín.',
    longDescription: 'Monoambiente de 30 m² con 1 baño, disponible en alquiler sobre el Boulevard San Martín de Ciudad Jardín. Ubicación práctica, cerca de comercios y accesos principales de la zona.',
    rooms: 1,
    bedrooms: 0,
    bathrooms: 1,
    garages: 0,
    coveredArea: 30,
    totalArea: 30,
    age: 0,
    condition: 'bueno',
    features: [],
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1400&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1489171078254-c3365d6e359f?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=1200&auto=format&fit=crop',
    ],
    featured: false,
    creditReady: false,
    reserved: false,
    isNew: false,
    location: { lat: -34.5991, lng: -58.5978 },
    propertyCode: 'TP-007',
    createdAt: '2026-08-18',
  },
]

export const services: Service[] = [
  {
    id: '1',
    title: 'Comprar',
    description: 'Encontrá la propiedad indicada para vos.',
    icon: 'search',
    href: '/comprar',
  },
  {
    id: '2',
    title: 'Vender',
    description: 'Comercializamos tu propiedad con estrategia, presentación profesional y seguimiento personalizado.',
    icon: 'home',
    href: '/contacto?motivo=vender',
  },
  {
    id: '3',
    title: 'Alquilar',
    description: 'Propiedades seleccionadas y acompañamiento durante todo el proceso.',
    icon: 'key',
    href: '/alquilar',
  },
  {
    id: '4',
    title: 'Tasaciones',
    description: 'Conocé el valor real de mercado de tu propiedad.',
    icon: 'chart',
    href: '/tasaciones',
  },
  {
    id: '5',
    title: 'Apto crédito',
    description: 'Encontrá propiedades compatibles con financiación bancaria.',
    icon: 'shield',
    href: '/apto-credito',
  },
  {
    id: '6',
    title: 'Asesoramiento',
    description: 'Acompañamiento profesional durante toda la operación.',
    icon: 'users',
    href: '/servicios',
  },
]

export const zones: Zone[] = [
  {
    id: '1',
    name: 'Ciudad Jardín',
    description: 'Calles arboladas, casas y dúplex consolidados. Nuestra zona de mayor trayectoria.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=ciudad-jardin',
  },
  {
    id: '2',
    name: 'El Palomar',
    description: 'Conectividad, comercios y una comunidad consolidada.',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=el-palomar',
  },
  {
    id: '3',
    name: 'Caseros',
    description: 'Vida de barrio, cercanía y accesos directos a la Ciudad.',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=caseros',
  },
  {
    id: '4',
    name: 'Villa Bosch',
    description: 'Una de las zonas de mayor crecimiento de Zona Oeste.',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=villa-bosch',
  },
  {
    id: '5',
    name: 'Martín Coronado',
    description: 'Barrios residenciales tranquilos, cerca de todo.',
    image: 'https://images.unsplash.com/photo-1600585153490-76fb20a32601?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=martin-coronado',
  },
  {
    id: '6',
    name: 'Hurlingham',
    description: 'Espacios verdes y una fuerte identidad de club de campo.',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=hurlingham',
  },
  {
    id: '7',
    name: 'San Martín',
    description: 'Centro comercial y administrativo de Zona Oeste.',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=900&auto=format&fit=crop',
    href: '/propiedades?zona=san-martin',
  },
]

export const propertyTypes = [
  { value: 'casa', label: 'Casa' },
  { value: 'departamento', label: 'Departamento' },
  { value: 'duplex', label: 'Dúplex' },
  { value: 'ph', label: 'PH' },
  { value: 'lote', label: 'Lote' },
  { value: 'oficina', label: 'Oficina' },
  { value: 'local', label: 'Local' },
  { value: 'cochera', label: 'Cochera' },
  { value: 'galpon', label: 'Galpón' },
]

export const operationTypes = [
  { value: 'venta', label: 'Venta' },
  { value: 'alquiler', label: 'Alquiler' },
  { value: 'temporal', label: 'Temporal' },
]

export const neighborhoods = [
  { value: 'ciudad-jardin', label: 'Ciudad Jardín' },
  { value: 'el-palomar', label: 'El Palomar' },
  { value: 'caseros', label: 'Caseros' },
  { value: 'villa-bosch', label: 'Villa Bosch' },
  { value: 'martin-coronado', label: 'Martín Coronado' },
  { value: 'hurlingham', label: 'Hurlingham' },
  { value: 'san-martin', label: 'San Martín' },
]

export const features = [
  { value: 'balcon', label: 'Balcón' },
  { value: 'terraza', label: 'Terraza' },
  { value: 'patio', label: 'Patio' },
  { value: 'jardin', label: 'Jardín' },
  { value: 'parrilla', label: 'Parrilla' },
  { value: 'pileta', label: 'Pileta' },
  { value: 'lavadero', label: 'Lavadero' },
  { value: 'cocina-separada', label: 'Cocina Separada' },
  { value: 'dependencia', label: 'Dependencia' },
  { value: 'seguridad', label: 'Seguridad' },
  { value: 'aire-acondicionado', label: 'Aire Acondicionado' },
  { value: 'calefaccion', label: 'Calefacción' },
  { value: 'gimnasio', label: 'Gimnasio' },
  { value: 'quincho', label: 'Quincho' },
  { value: 'ascensor', label: 'Ascensor' },
  { value: 'club-house', label: 'Club House' },
]
